ALTER TABLE "FOREST"."PERSON_GROUPS" DROP CONSTRAINT FK_PERSON_GROUPS_PERSON
ALTER TABLE "FOREST"."PERSON_GROUPS" DROP CONSTRAINT FK_PERSON_GROUPS_GROUPS
ALTER TABLE "FOREST"."CUSTOMER_ORDER" DROP CONSTRAINT FK_CUSTOMER_ORDER_ORDER_STATUS1
ALTER TABLE "FOREST"."CUSTOMER_ORDER" DROP CONSTRAINT FK_CUSTOMER_ORDER_CUSTOMER1
ALTER TABLE "FOREST"."PRODUCT" DROP CONSTRAINT FK_PRODUCT_CATEGORY
ALTER TABLE "FOREST"."ORDER_DETAIL" DROP CONSTRAINT FK_ORDER_DETAIL_PRODUCT
ALTER TABLE "FOREST"."ORDER_DETAIL" DROP CONSTRAINT FK_ORDER_DETAIL_ORDER

DROP TABLE "FOREST"."PERSON_GROUPS"
DROP TABLE "FOREST"."PERSON"
DROP TABLE "FOREST"."GROUPS"
DROP TABLE "FOREST"."ORDER_DETAIL"
DROP TABLE "FOREST"."CUSTOMER_ORDER"
DROP TABLE "FOREST"."ORDER_STATUS"
DROP TABLE "FOREST"."PRODUCT"
DROP TABLE "FOREST"."CATEGORY"